name: TryJumpCoreModule
author: freggy
version: 1.0
main: de.bergwerklabs.tryjump.core.TryJumpSession

depend: [SpigotCommons, BedrockSessionService, SchematicService]

commands:
     start:
          description: Start
          usage: /start
     stats:
          description: Stats
          usage: /stats
     skip:
          description: Skip
          usage: /skip
     fix:
          description: Fix
          usage: /fix
     log:
          description: Log
          usage: /log
     force:
           description: Log
           usage: /log