name: Gameserver
author: nexotekHD
version: 1.0
main: de.bergwerklabs.tryjump.gameserver.TryJump

depend: ["LABS_Util","LABS_Chat","LABS_Nick"]

commands:
     start:
          description: Start
          usage: /start
     stats:
          description: Stats
          usage: /stats
     skip:
          description: Skip
          usage: /skip