name: Gameserver
author: nexotekHD, freggy
version: 1.0
main: de.bergwerklabs.tryjump.gameserver.TryJump

depend: [LABS_Util, zPermissions, AtlantisBukkitClient, SpigotChatCommons, SpigotCommons, NickTool]

commands:
     start:
          description: Start
          usage: /start
     stats:
          description: Stats
          usage: /stats
     skip:
          description: Skip
          usage: /skip
     fix:
          description: Fix
          usage: /fix
     log:
          description: Log
          usage: /log
     force:
           description: Log
           usage: /log