name: Gameserver
author: nexotekHD
version: 1.0
main: de.bergwerklabs.tryjump.gameserver.TryJump

depend: [LABS_Util, LABS_Nick, LABS_Chat, zPermissions]

commands:
     start:
          description: Start
          usage: /start
     stats:
          description: Stats
          usage: /stats
     skip:
          description: Skip
          usage: /skip
     fix:
          description: Fix
          usage: /fix
     log:
          description: Log
          usage: /log